"""remove_inbound_id_from_servers

Revision ID: 100052660595
Revises: 3f18fc961ae9
Create Date: 2025-11-28 18:34:56.523294

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '100052660595'
down_revision: Union[str, None] = '3f18fc961ae9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('servers', 'inbound_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('servers', sa.Column('inbound_id', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=False))
    # ### end Alembic commands ###

