"""add_pbk_to_servers

Revision ID: 13355c746cc8
Revises: 100052660595
Create Date: 2025-11-28 19:31:33.238436

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13355c746cc8'
down_revision: Union[str, None] = '100052660595'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('servers', sa.Column('pbk', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('servers', 'pbk')
    # ### end Alembic commands ###

