"""remove_subscription_url_from_servers

Revision ID: 3f18fc961ae9
Revises: 2bf96a8861f4
Create Date: 2025-11-28 18:26:01.461035

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f18fc961ae9'
down_revision: Union[str, None] = '2bf96a8861f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('servers', 'subscription_url')
    op.drop_index('ix_subscriptions_user_server', table_name='subscriptions')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_subscriptions_user_server', 'subscriptions', ['user_id', 'server_id'], unique=False)
    op.add_column('servers', sa.Column('subscription_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###

