"""add_notification_fields_to_subscriptions

Revision ID: add_notification_fields
Revises: 13355c746cc8
Create Date: 2025-01-27 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'add_notification_fields'
down_revision: Union[str, None] = '13355c746cc8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('notification_3_days_sent', sa.Boolean(), nullable=True, server_default='false'))
    op.add_column('subscriptions', sa.Column('notification_1_day_sent', sa.Boolean(), nullable=True, server_default='false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscriptions', 'notification_1_day_sent')
    op.drop_column('subscriptions', 'notification_3_days_sent')
    # ### end Alembic commands ###

