"""add_deletion_notification_fields_to_subscriptions

Revision ID: add_deletion_notification_fields
Revises: 8cc9f0fbf4fb
Create Date: 2025-01-27 12:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'add_deletion_notification_fields'
down_revision: Union[str, None] = '8cc9f0fbf4fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('notification_deletion_warning_1_sent', sa.Boolean(), nullable=True, server_default='false'))
    op.add_column('subscriptions', sa.Column('notification_deletion_warning_2_sent', sa.Boolean(), nullable=True, server_default='false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscriptions', 'notification_deletion_warning_2_sent')
    op.drop_column('subscriptions', 'notification_deletion_warning_1_sent')
    # ### end Alembic commands ###

